global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ngassamangela2@gmail.com'
  smtp_auth_username: 'ngassamangela2@gmail.com'
  smtp_auth_password: 'axkovpnlyyhhktwb'   # ← les 16 caractères sans espaces
  smtp_require_tls: true
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'ngassamangela2@gmail.com'
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['instance']
